// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_Oa0etxE0F-dMwnAoXP3oA_47A-t9Ac',
    appId: '1:595766370393:web:7ae2100e909dc89a6e9148',
    messagingSenderId: '595766370393',
    projectId: 'portfolio-rockstar978312',
    authDomain: 'portfolio-rockstar978312.firebaseapp.com',
    storageBucket: 'portfolio-rockstar978312.firebasestorage.app',
    measurementId: 'G-88RMNGRXWH',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJnhQXsLkeLj7gwGbuykqV4CpcPv2z9Q',
    appId: '1:595766370393:android:83c51001f78cb6cf6e9148',
    messagingSenderId: '595766370393',
    projectId: 'portfolio-rockstar978312',
    storageBucket: 'portfolio-rockstar978312.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYiBDoScrjXzHEzPOaze8STqCSorTWzs',
    appId: '1:595766370393:ios:ff8a492f57b86aa36e9148',
    messagingSenderId: '595766370393',
    projectId: 'portfolio-rockstar978312',
    storageBucket: 'portfolio-rockstar978312.firebasestorage.app',
    iosBundleId: 'com.portfolio.all.explore.protfoliowebsite',
  );

}