name: Build and Commit Flutter Web and APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allows the workflow to push commits to the repository
      pages: write    # Specifically grants write access for GitHub Pages deployments
      id-token: write # Recommended for OpenID Connect, used by GitHub Pages internally for enhanced security

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5' # This is good, should fix Dart SDK issue
          channel: 'stable' # Explicitly stating channel is good practice

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Prepare Web Build Folder
        run: |
          rm -rf web_build
          mkdir web_build
          cp -r build/web/* web_build/

      - name: Commit Built Artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add web_build 
          git commit -m "chore: update built web" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
